### ISSUE TITLE
Sonarqube report invalid location

### ISSUE THREAD

**Issue by LeoLogeart** [MobSF/mobsfscan#17]
Some vulnerabilities do not have a location, which is rejected by sonar:
```
{
      "engineId": "mobsfscan",
      "primaryLocation": null,
      "ruleId": "android_prevent_screenshot",
      "severity": "INFO",
      "type": "VULNERABILITY"
    },
    {
      "engineId": "mobsfscan",
      "primaryLocation": null,
      "ruleId": "android_root_detection",
      "severity": "INFO",
      "type": "VULNERABILITY"
    },
    {
      "engineId": "mobsfscan",
      "primaryLocation": null,
      "ruleId": "android_detect_tapjacking",
      "severity": "INFO",
      "type": "VULNERABILITY"
    },
    {
      "engineId": "mobsfscan",
      "primaryLocation": null,
      "ruleId": "android_certificate_pinning",
      "severity": "INFO",
      "type": "VULNERABILITY"
    },
    {
      "engineId": "mobsfscan",
      "primaryLocation": null,
      "ruleId": "android_safetynet_api",
      "severity": "INFO",
      "type": "VULNERABILITY"
    },
    {
      "engineId": "mobsfscan",
      "primaryLocation": null,
      "ruleId": "android_certificate_transparency",
      "severity": "INFO",
      "type": "VULNERABILITY"
    }
```

Issues with no file location should either be removed or use a generic location.

**Comment by fnxpt** [comment]
I have a branch with this fixed, my main issue is what file should we use for this. Initially I thought the project file, but maybe this should be a parameter or a configuration on the yaml

**Comment by LeoLogeart** [comment]
Having a parameter in the configuration file seems like a must-have for this. However, for the default behavior, I'm not sure we can rely on the project file.
It may be simpler to just exit with a warning for the sonarqube format when the new parameter is not set.

**Comment by fnxpt** [comment]
I created a PR for this issue, please have a look. If you don't pass the parameter it will produce a json with an empty file path in these scenarios.
I can also add a warning in there if this is empty but I don't think we should exit, since the JSON produced is a valid one and will not break sonarqube scan

**Comment by ajinabraham** [comment]
These are best practices rules, for example https://github.com/MobSF/mobsfscan/tree/main/mobsfscan/rules/semgrep/best_practices

They will get triggered only if these patterns are not found after scanning the entire source code. So it is expected to not have a file attached the finding. I will take a look at the PR.

You could explicitly ignore those rules from the scan using the `.mobsf` config file.

**Comment by fnxpt** [comment]
I understood that but if there isn’t a file it will be impossible to import these into sonarqube.

**Comment by fnxpt** [comment]
@ajinabraham can you check the updated PRs

**Comment by ajinabraham** [comment]
Please see: https://github.com/MobSF/mobsfscan/pull/20#issuecomment-1024989651
