### ISSUE TITLE
Link to documentation for rules

### ISSUE THREAD

**Issue by FlashSheridan** [MobSF/mobsfscan#23]
My first scan reported [four issues](https://github.com/FlashSheridan/EncycloClip/security/code-scanning/1?query=ref%3Arefs%2Fheads%2Fmaster), which sound irrelevant, but I cannot find out what they actually mean.  There should be a link in, e.g. ‘[This app does not have Jailbreak detection capabilities](https://github.com/FlashSheridan/EncycloClip/security/code-scanning/1?query=ref%3Arefs%2Fheads%2Fmaster)’ to what the rule means and why I should worry; but not even a DuckDuckGo or Google search for ‘"mobsf" "ios_jailbreak_detect"’ turned up anything.

**Comment by ajinabraham** [comment]
All the rules have a reference URL for example https://github.com/MobSF/owasp-mstg/blob/master/Document/0x06j-Testing-Resiliency-Against-Reverse-Engineering.md#jailbreak-detection-mstg-resilience-1

**Comment by FlashSheridan** [comment]
Where is the link in the page I posted: 
“There should be a link in, e.g. ‘This app does not have Jailbreak detection capabilities’ [https://github.com/FlashSheridan/EncycloClip/security/code-scanning/1?query=ref%3Arefs%2Fheads%2Fmaster]’”?

**Comment by ajinabraham** [comment]
I do not have access to your repository. Assuming you are using Github code scanning, I think we report the reference URL as metadata in SARIF format to Github. 
https://github.com/MobSF/mobsfscan/blob/a60d10a83af68e23e0b30611c6515da604f06f65/mobsfscan/rules/patterns/ios/objectivec/best_practices.yaml#L61

It might happen that the Github UI is not reading the metadata.
