### ISSUE TITLE
Filter rules pre-scan

### ISSUE THREAD

**Issue by kiwiz** [MobSF/mobsfscan#25]
Currently, rules are filtered after the scan - meaning that a lot of unnecessary processing is done. For my Android codebase the semgrep rules run very slowly.

It would be nice to have the ability to filter out rules prior to execution. I'm not sure if this should be an addition option, or if the current filter mode should be updated.

**Comment by ajinabraham** [comment]
We use libsast and semgrep for SAST. I will check if semgrep supports excluding rules before scanning. IIRC they used to do filtering post scanning. I will check and get back.

**Comment by kiwiz** [comment]
According to https://semgrep.dev/docs/cli-reference/, there is no way to filter out rules. :[

So, it seems like we'd have to create a temporary directory with a list of rules to execute.

**Comment by ajinabraham** [comment]
Please bump it here: https://github.com/returntocorp/semgrep/issues/2530
I cannot do much without upstream support to properly support this change.

**Comment by kiwiz** [comment]
Will do, thanks for the reference.
