### ISSUE TITLE
Cannot output the scan result to HTML file

### ISSUE THREAD

**Issue by misa335** [MobSF/mobsfscan#26]
I tried to output the scan results using the command line options described in README, but it didn't work.
If I try to output to HTML locally, I can see the same results in the terminal as when I run `mobsfscan .`.
If I try it on Circle CI, no file will be created and the result of the CI step execution also will be just as when I run `mobsfscan .`.
It would be great to be able to output to HTML file (or PDF file) on the CI tools using the command line.

**Comment by ajinabraham** [comment]
Works fine at my end
```(venv) ➜  mobsfscan . --html -o result.html
- Pattern Match ████████████████████████████████████████████████████████████ 67
- Semantic Grep  61

mobsfscan: v0.0.8 | Ajin Abraham | opensecurity.in
(venv) ➜  tail -f result.html
<tbody>
<tr><td>RULE ID     </td><td>android_safetynet_api                                                                                                                                                                                                                                       </td></tr>
<tr><td>CWE         </td><td>CWE-353 Missing Support for Integrity Check
The file will be generated only if there are some findings.
```

**Comment by misa335** [comment]
I could generate html file. I'm going to close this issue. Thank you!
