### ISSUE TITLE
GitHub Action Private

### ISSUE THREAD

**Issue by Moose0621** [MobSF/mobsfscan#3]
Hi! 👋 - I'm trying to use the GH Action you reference in the workflow, but it appears the repository is private still.  Could I be added as a contributor as I'm interested in getting this working for a project I'm working on.  

If you're able to make it public as well that's even better!

[My Test Repository](https://github.com/Moose0621/iGoat-Swift)

**Comment by ajinabraham** [comment]
Hi @Moose0621 The action is not published yet. It's a work in progress.

For now you will have to use the parent project https://github.com/MobSF/Mobile-Security-Framework-MobSF

or

https://github.com/fundacaocerti/mobsf-action
