### ISSUE TITLE
SSLContext.init "null" finding in accept_self_signed.yaml

### ISSUE THREAD

**Issue by coheigea** [MobSF/mobsfscan#33]
In accept_self_signed.yaml there is:
```
          - pattern: |
              $Y = SSLContext.getInstance(...);
              ...
              $Y.init(null, ...);
          - pattern: |
              $Y = $S.SSLContext.getInstance(...);
              ...
              $Y.init(null, ...);
```
However, setting null as the first parameter just means that no KeyManagers are configured, which is the normal case for TLS clients https://docs.oracle.com/javase/8/docs/api/javax/net/ssl/SSLContext.html#init-javax.net.ssl.KeyManager:A-javax.net.ssl.TrustManager:A-java.security.SecureRandom-
I would recommend just removing these two patterns - I can submit a PR if you agree.

**Comment by ajinabraham** [comment]
Thanks for the report. I will take a look when I have some bandwidth.

**Comment by ajinabraham** [comment]
Upon looking into this, this seems like a common pattern in accepting self signed certificates.
Here is the unit test we use: https://github.com/MobSF/mobsfscan/blob/main/tests/assets/rules/semgrep/network/accept_self_signed.java

I suggest you [suppress](https://github.com/MobSF/mobsfscan#suppress-findings) this as a false positive.
