### ISSUE TITLE
Kotlin and Swift scans returning differerent codes.

### ISSUE THREAD

**Issue by OlivettiOriana** [MobSF/mobsfscan#36]
Hi, 
I have been digging for a while and I have not been able to find the reason why when running mobsf with a swift project, the return code is 0, and when I do it with a kotlin project, the return code is 1, even though it seems to run successfully. 

I have a docker container which clones the mobile repos and runs mobsf. I am currently calling it with the python module subprocess like this. 
`process = subprocess.run(
                "mobsfscan --sarif -o report.sarif <mobilerepo>", 
                shell=True, 
                capture_output=True,
                universal_newlines=True,
                timeout=None
                )`
                
and when I look at the process.returncode I get 1 for the kotlin project and 0 for the swift project, even though both scans seems to run successfully. 
Unfortunately, I am not able to share the projects, but I was wondering if it is something that is happening at the mobsf sourcecode level, or something that I'm doing wrong. 

Thanks in advance!

**Comment by ajinabraham** [comment]
The exit codes depends on the scan results.

If the scan results have findings with `ERROR` severity, the exit code thrown will be `1` and `0` for the rest.
You can control the exit code for `WARNING` with the [-w](https://github.com/MobSF/mobsfscan/blob/8b497fab9b07e0d60f0a07e2943318288ba0fa4b/mobsfscan/__main__.py#L54) parameter.
https://github.com/MobSF/mobsfscan/blob/8b497fab9b07e0d60f0a07e2943318288ba0fa4b/mobsfscan/__main__.py#L25-L26

**Comment by ajinabraham** [comment]
It depends on the error. it will be non zero though.
