### ISSUE TITLE
Make ignore-filenames and ignore-paths support wildcards

### ISSUE THREAD

**Issue by TimothyChilvers** [MobSF/mobsfscan#48]
I would like to set up an exclusion so that all paths under a subdirectory named tests are ignored without explicitly setting up each exclusion.

Given filepaths:
./module/tests
./module/source
./another-module/tests
./another-module/source

And given ignore-paths:
./*/tests

MobSFScan should only run against `./module/source` and `./another-module/source`

**Comment by ajinabraham** [comment]
I will take a look at this. Currently libsast doesn't support glob https://github.com/ajinabraham/libsast/blob/ab406dcc45319d133e296d8594b8aff035036d71/libsast/scanner.py#L86

**Comment by ajinabraham** [comment]
You could just use `/tests` or `tests` under `ignore-paths` instead of glob.

**Comment by ajinabraham** [comment]
We support regex, but not glob.
