### ISSUE TITLE
Can it scan ios and android source code at the same time?

### ISSUE THREAD

**Issue by chenbokun97** [MobSF/mobsfscan#53]
Here is the issue, our app is written by flutter.
And I want to scan the third-party code, which includes both ios and android
while the scan output only includes android
<img width="436" alt="image" src="https://user-images.githubusercontent.com/84758580/217987176-898ef07e-b5b1-4f09-8e4e-bba99e7ef4b5.png">

I have no idea why this happen, could you please help me?

**Comment by ajinabraham** [comment]
The way in which mobsfscan is written, it tries to detect Android/iOS source code by looking at the extension and stick with one set of rules. If you have both Android and iOS source code, you need to scan these directories separately.

**Comment by chenbokun97** [comment]
thanks, but how can I specify the scan type?I can not find the config rule. ios and android packages are mixed up in a plugin floder and I have to scan all the plugins.

**Comment by ajinabraham** [comment]
You cannot at this time. I can take this as a feature request.

**Comment by chenbokun97** [comment]
thanks a lot!

**Comment by ajinabraham** [comment]
This now available in mobsfscan 0.3.0. You can use `--type android` or `--type ios` to force a platform specific ruleset.
