### ISSUE TITLE
semgrep.error.SemgrepError: Error while running rules: 0 bytes read on a total of 2 expected bytes

### ISSUE THREAD

**Issue by gxwilkerson33** [MobSF/mobsfscan#54]
v0.2.0
scanning android project root folder and specific files using CLI. tried on multiple projects for our team. 
the issue is:
- we cannot run the scan due to the error in the title. this error is on Semantic Grep 8. when running with --sonarqube the grep number is not output. 
- Looking for resolution to incorporate this into CI/CD pipe line

**Comment by gxwilkerson33** [comment]
can be closed. issue with mac.

**Comment by ajinabraham** [comment]
Thanks for the detailed troubleshooting.
