### ISSUE TITLE
How to send the --sonarqube output to my Sonarqube instance?

### ISSUE THREAD

**Issue by matheusinfosec** [MobSF/mobsfscan#55]
Hi Ajin

I'm trying to integrate the mobsfscan in my CI/CD by GitActions, however, I can't see anywhere how to send the output to my SonarQube instance, Is there somewhere a tutorial that teaches how to send the scan's results to SonarQube?

**Comment by ajinabraham** [comment]
This is out of scope for this project. It should be a documented somewhere in sonarqube.
