### ISSUE TITLE
Android XML checks failed 

### ISSUE THREAD

**Issue by L3m0nb4tt3ry** [MobSF/mobsfscan#58]
Mobsfscan failed with an error: `Android XML checks failed. Please report this issue to the mobsfscan project.`

We began experiencing issues with `mobsfscan` after adding beta support for Android XML checks. Our Android repository consists of multiple modules, including `app, extensions, app-permissions,` and others. Some of these submodules have their own `AndroidManifest.xml` files, while others do not.

`mobsfscan` does not throw an error when scanning only the `app` or any other subdirectory. However, it fails when attempting to scan the entire repository

**Comment by L3m0nb4tt3ry** [comment]
@ajinabraham Here is the problematic manifest file. If I remove this file, scan completes without any error.
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android">

    <application>
        android:allowBackup="false"
        android:usesCleartextTraffic="false"
    </application>

</manifest>
```

**Comment by ajinabraham** [comment]
This seems to be an invalid manifest file. The correct syntax should be something like 

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
    <application
        android:allowBackup="false"
        android:usesCleartextTraffic="false">
    </application>
</manifest>
```

**Comment by L3m0nb4tt3ry** [comment]
My bad I missed it, can confirm the scan runs fine right now, none the less do you think it would be a good idea to skip the file if the syntax is not correct or the file is malformed ?
