### ISSUE TITLE
No issues found when running scan

### ISSUE THREAD

**Issue by jgardezy** [MobSF/mobsfscan#60]
Hi I'm running into an issue when running the scan. I have an apk file which I'm trying to scan by using the command 

> mobsfscan app.apk 
The response is that there are no issues found, however when I use the MobSF UI it finds a bunch of issues. So I'm not sure what's going wrong here.

**Comment by jgardezy** [comment]
and if I scan the /android folder in my project, I'm hit with a bunch of errors.
`Exception in thread Thread-1:
`
`semgrep.error.SemgrepError: Error while running rules: 0 bytes read on a total of 2 expected bytes
`
`TypeError: 'NoneType' object is not subscriptable
`

**Comment by ajinabraham** [comment]
mobsfscan does not support APK or any other binaries format, but just source code.
