### ISSUE TITLE
CodeQL Action Deprecation

### ISSUE THREAD

**Issue by sathish-kishore** [MobSF/mobsfscan#61]
Error: This version of the CodeQL Action was deprecated on January 18th, 2023, and is no longer updated or supported. For better performance, improved security, and new features, upgrade to v2. For more information, see https://github.blog/changelog/2023-01-18-code-scanning-codeql-action-v1-is-now-deprecated/

Error: codeql/upload-sarif action failed: HttpError: Resource not accessible by integration

**Comment by sathish-kishore** [comment]
[](url)

**Comment by sathish-kishore** [comment]
These entries need to be replaced with their v2 equivalents:

github/codeql-action/init@v2
github/codeql-action/autobuild@v2
github/codeql-action/analyze@v2
github/codeql-action/upload-sarif@v2

**Comment by ajinabraham** [comment]
Thanks for reporting. Updated the GitHub actions documentation.
