### ISSUE TITLE
SonarQube compatible format is not working

### ISSUE THREAD

**Issue by iducool** [MobSF/mobsfscan#64]
Getting following exception,

<img width="1350" alt="Screenshot 2023-05-23 at 2 57 10 PM" src="https://github.com/MobSF/mobsfscan/assets/1644787/99757891-0332-4fce-90f0-87b491851cb4">

Here is a command that i used to generate report

`mobsfscan ./  --output ./sonar-reports/mobsf_report --sonarqube`

Here is an excerpt of generated file
```
{
  "issues": [
    {
      "engineId": "mobsfscan",
      "primaryLocation": {
        "filePath": "OTech/AppDelegate.swift",
        "message": "The App logs information. Sensitive information should never be logged. [print(\"Activity\")]",
        "textRange": {
          "endLine": 382,
          "startLine": 382
        }
      },
      "ruleId": "ios_log",
```

**Comment by ajinabraham** [comment]
Hi there,

It seems one of the finding doesn't have a `filePath` associated. It's normal for mobsfscan to report such an issue, but sonar seems to not accept it. You could disable that rule and generate the report for sonarqube.
