### ISSUE TITLE
Semantic Grep takes forever

### ISSUE THREAD

**Issue by OgnjenKop** [MobSF/mobsfscan#72]
I've noticed that my CI pipelines started timing out for a few months already. The reason is that running mobscan against my Android repo takes forever, namely the semantic greb stage.

Pattern match is done quickly, but semantic greb just keeps going on and on. The counter increases indefinitely.

**Comment by ajinabraham** [comment]
We need to isolate this to a file to troubleshoot what is happening.

**Comment by ajinabraham** [comment]
Closing this since it's not actionable unless we get a sample to replicate this.
