### ISSUE TITLE
Android API 34 missing from ANDROID_API_LEVEL_MAP

### ISSUE THREAD

**Issue by arttujo** [MobSF/mobsfscan#76]
It would seem that in the latest [pull request](https://github.com/MobSF/mobsfscan/pull/75/files) and with the new `ANDROID_API_LEVEL_MAP` there seems to be an issue where if your `targetSdk = 34` all the checks will default to API lvl `26` due to `34` missing from the definition.

**Comment by ajinabraham** [comment]
Thanks for reporting this, I will update the `ANDROID_API_LEVEL_MAP`. 

It seems like if the `targetSdk` is not determined from the manifest file, `minSdk` is used as target SDK. `ANDROID_API_LEVEL_MAP` is not considered for determining `targetSdk`

**Comment by ajinabraham** [comment]
Addressed in https://github.com/MobSF/mobsfscan/pull/77

**Comment by phileo** [comment]
>It seems like if the targetSdk is not determined from the manifest file, minSdk is used as target SDK.

This will lead to a false failure in `TaskHijackingChecks`  because `minSdk`=26 but `targetSdk`=34 defined in build.gradle.

Is there a way to have `scan_manifest` or `TaskHijackingChecks` instead read from build.gradle in order to obtain the correct `minSdk` version?

**Comment by phcannesson** [comment]
Hello @ajinabraham, 

I'm seeing the same false positives for `TaskHijackingChecks` because my target SDK is set in `build.gradle`.

Could this be reopened maybe ?
