### ISSUE TITLE
False Positive Issues on Android 34

### ISSUE THREAD

**Issue by Heckfer** [MobSF/mobsfscan#78]
We've recently updated our `targetSdk` from `33` to `34` and all was fine while using `mobsfscan` version `v0.3.4`.
Once we updated to `mobsfscan` version `v0.3.5` we started having 2 false positives in our CI:
- android_task_hijacking1
- android_task_hijacking2

The reason I say it's a false positive is that the problem is saying this only happens on `targetSdk < 28 and targetSdk < 29` respectively. Also, if I change my `targetSdk` version back to `33` the problems go away.

**Comment by Heckfer** [comment]
I forgot to mention that this was not fixed on version `v0.3.6`

**Comment by ajinabraham** [comment]
Can you share a sample problamatic manifest file for troublehsooting this?

**Comment by joost-klitsie** [comment]
This is still a thing with version 0.3.8

**Comment by ajinabraham** [comment]
What everyones `<uses-sdk>` like?
Something like this will trigger the rule since the minSdk is <=28` <uses-sdk android:minSdkVersion="28" android:targetSdkVersion="34" />`
