### ISSUE TITLE
Ignoring errors by severity

### ISSUE THREAD

**Issue by ansidorov** [MobSF/mobsfscan#9]
Good afternoon.
I would like to have a flag that I can use to ignore INFO level errors. Is there such a feature? Is it planned? Or what part of the code should I look into to add such a function?

Thank you very much.

**Comment by ajinabraham** [comment]
Hi @ansidorov mobsfscan does not have a feature to ignore by level.
You can ignore info rules by adding it to `ignore-rules:` section in `. mobsf` file
https://github.com/MobSF/mobsfscan#configure-mobsfscan

To implement this feature, you might have to modify the logic in the following location.

https://github.com/MobSF/mobsfscan/blob/ac72ac6552f5d0cea0602a28980a5b102bc96f31/mobsfscan/mobsfscan.py#L148
https://github.com/MobSF/mobsfscan/blob/ac72ac6552f5d0cea0602a28980a5b102bc96f31/mobsfscan/utils.py#L14
https://github.com/MobSF/mobsfscan/blob/ac72ac6552f5d0cea0602a28980a5b102bc96f31/mobsfscan/__main__.py#L29
