### ISSUE TITLE
Restrict output width?

### ISSUE THREAD

**Issue by below** [MobSF/mobsfscan#92]
I am running mobsfscan in a gitlab pipeline, but for some reason, mobsfscan assumes a very wide terminal.

I would like to restrict the width of the output.

`stty` fails, because input is not a terminal.

Are there ways inside or outside of mobsfscan to restrict the output width?

**Comment by ajinabraham** [comment]
The width is assumed based on the internal libs and the length of the files/findings.

You could try using a different output format in this case.

```
 --json                set output format as JSON
  --sarif               set output format as SARIF 2.1.0
  --sonarqube           set output format compatible with SonarQube
  --html                set output format as HTML
  ```
